### ISSUE TITLE
Repo is empty, but it's already used in the installation guide

### ISSUE THREAD

**Issue by arne-cl** [quantifiedcode/quantifiedcode-docker#1]
The repo is already used in the docker section of the official installation guide:
https://docs.quantifiedcode.com/download#docker

**Comment by adewes** [comment]
Hey @arne-cl , the OSS version is not yet available for download (we're currently preparing it), so the site is not yet for public use ;) Seems that we had a slight misconfiguration on our webserver, which led https://docs.quantifiedcode.com to point to the new OSS website, I fixed that and I'll notify you as soon as the docker repository is available for testing.

Where did you find the link to https://docs.quantifiedcode.com if I may ask (so that I can fix it)?

Best
Andreas

**Comment by arne-cl** [comment]
Dear Andreas,

thank you for the fast response. I don't remember how I got to https://docs.quantifiedcode.com/.
I am using quantifiedcode for my open-source projects and was looking for a way to introduce the tool
to the company I work for.

Best regards
Arne

**Comment by adewes** [comment]
Ok thanks for reporting this in any case, if you're interested in testing the CE Edition please send me an e-mail at andreas@quantifiedcode.com, I'll be happy to set you up as soon as it's available.
